name: SoloSec Security Scan
description: Run SoloSec (Trivy + Semgrep + Gitleaks + optional ZAP).

inputs:
  url:
    description: "Optional DAST target URL"
    required: false
  upload-artifact:
    description: "Upload reports"
    default: "true"
  artifact-name:
    description: "Artifact name"
    default: "solosec-report"

runs:
  using: composite
  steps:
    - name: Build SoloSec
      shell: bash
      run: docker build -t solosec:action "${GITHUB_ACTION_PATH}"

    - name: Run SoloSec
      shell: bash
      env:
        INPUT_URL: ${{ inputs.url }}
      run: |
        URL="$INPUT_URL"
        ARGS=()
        if [ -n "$URL" ]; then ARGS+=(--url "$URL"); fi

        docker run --rm \
          -v "${GITHUB_WORKSPACE}:/src" \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e GITHUB_WORKSPACE="${GITHUB_WORKSPACE}" \
          solosec:action "${ARGS[@]}"

    - name: Upload reports
      if: ${{ always() && inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          security_audit.json
          .security_reports/**
